name: Fetch Latest Trends

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:  # Enables manual triggering

jobs:
  fetch-trends:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: Sudzv1606/TrendPilot

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Fetch and analyze trends
        run: |
          echo "Checking environment variables..."
          echo "OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}"
          echo "REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}"
          echo "Running trend fetch script..."
          node scripts/fetch-trends.js
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}

      - name: Update latest trends file
        run: |
          echo "Updating latest trends file..."
          # Copy the latest trends file to trends-latest.json
          ls -la data/
          if ls data/trends-*.json 1> /dev/null 2>&1; then
            LATEST_FILE=$(ls -t data/trends-*.json | head -1)
            echo "Latest file: $LATEST_FILE"
            cp "$LATEST_FILE" data/trends-latest.json
            echo "Updated trends-latest.json"
          else
            echo "No trends files found"
          fi

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update trend data $(date)"
            git push
          fi
